/*
 jQRangeSlider Copyright (C) Guillaume Gautreau 2010, 2011
 A javascript slider selector that supports dates

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
var d=null;
(function(c){c.Da("ui.rangeSlider",{options:{e:{min:0,max:100},w:{min:20,max:50},S:d,A:4,d:!0,z:"show",G:d,da:0,ea:400,ba:200},c:d,n:d,g:d,h:d,t:d,j:d,d:d,a:d,i:{min:!1,max:!1},xa:{min:!1,max:!1},Q:0,u:0,I:0,Fa:function(){this.c=this.options.w;this.a={left:d,right:d,q:!0,r:!0};this.d={left:d,right:d};this.i={min:!1,max:!1};this.xa={min:!1,max:!1};this.g=c("<div class='ui-rangeSlider-handle  ui-rangeSlider-leftHandle' />").draggable({axis:"x",aa:"parent",ca:c.f(this.X,this),stop:c.f(this.Y,this)}).b("position",
"absolute");this.h=c("<div class='ui-rangeSlider-handle ui-rangeSlider-rightHandle' />").draggable({axis:"x",aa:"parent",ca:c.f(this.X,this),stop:c.f(this.Y,this)}).b("position","absolute");this.t=c("<div class='ui-rangeSlider-innerBar' />").b("position","absolute").b("top",0).b("left",0);this.j=c("<div class='ui-rangeSlider-container' />").b("position","absolute");this.n=c("<div class='ui-rangeSlider-bar' />").draggable({axis:"x",ca:c.f(this.ja,this),stop:c.f(this.ka,this),aa:this.j}).b("position",
"absolute").bind("mousewheel",c.f(this.va,this));this.d.left=c("<div class='ui-rangeSlider-arrow ui-rangeSlider-leftArrow' />").b("position","absolute").b("left",0).bind("mousedown",c.f(this.ra,this));this.d.right=c("<div class='ui-rangeSlider-arrow ui-rangeSlider-rightArrow' />").b("position","absolute").b("right",0).bind("mousedown",c.f(this.sa,this));c(document).bind("mouseup",c.f(this.ta,this));this.j.append(this.g).append(this.h).append(this.t).append(this.n);this.element.append(this.j).append(this.d.left).append(this.d.right).p("ui-rangeSlider").bind("mousewheel",
c.f(this.wa,this));this.element.b("position")!="absolute"&&this.element.b("position","relative");this.options.d?this.element.p("ui-rangeSlider-withArrows"):(this.d.left.b("display","none"),this.d.right.b("display","none"),this.element.p("ui-rangeSlider-noArrow"));this.options.z!="hide"?this.U():this.K();c(window).Ia(c.f(this.pa,this));setTimeout(c.f(this.L,this),1);setTimeout(c.f(this.oa,this),1)},L:function(){this.j.b("width",this.element.width()-this.j.outerWidth(!0)+this.j.width());this.t.b("width",
this.j.width()-this.t.outerWidth(!0)+this.t.width())},oa:function(){this.m(this.options.w.min,this.options.w.max)},O:function(a,b){if(a=="defaultValues"){if(typeof b.min!="undefined"&&typeof b.max!="undefined"&&parseFloat(b.min)===b.min&&parseFloat(b.max)===b.max)this.options.w=b}else if(a=="wheelMode"&&(b=="zoom"||b=="scroll"||b===d))this.options.S=b;else if(a=="wheelSpeed"&&!isNaN(parseFloat(b))&&Math.abs(parseFloat(b))<=100)this.options.A=parseFloat(b);else if(a=="arrows"&&(b===!0||b===!1)&&b!=
this.options.d)b?(this.element.v("ui-rangeSlider-noArrow").p("ui-rangeSlider-withArrows"),this.d.left.b("display","block"),this.d.right.b("display","block")):(this.element.p("ui-rangeSlider-noArrow").v("ui-rangeSlider-withArrows"),this.d.left.b("display","none"),this.d.right.b("display","none")),this.options.d=b,this.L(),this.o();else if(a=="valueLabels"&&(b=="hide"||b=="show"||b=="change"))this.options.z=b,b!="hide"?this.U():this.K();else if(a=="formatter"&&b!==d&&typeof b=="function")this.options.G=
b,this.o();else if(a=="bounds"&&typeof b.min!="undefined"&&typeof b.max!="undefined"&&parseFloat(b.min)===b.min&&parseFloat(b.max)===b.max&&b.min<b.max)this.options.e=b,this.m(this.c.min,this.c.max)},C:function(a){return(a-this.options.e.min)*(this.j.innerWidth()-1)/(this.options.e.max-this.options.e.min)},D:function(a){return a*(this.options.e.max-this.options.e.min)/(this.j.innerWidth()-1)+this.options.e.min},F:function(a,b){this.P(a,b);this.o();return this.c},s:function(a){this.element.Ja(a,{label:this.element,
m:this.m()})},o:function(){var a=this.C(this.c.min),b=this.C(this.c.max);this.M();this.n.b("left",a).b("width",b-a+this.n.width()-this.n.outerWidth(!0)+1)},M:function(){var a=this.C(this.c.min),b=this.C(this.c.max)-this.h.outerWidth(!0)+1;this.g.b("left",a);this.h.b("left",b);this.$()},ja:function(a,b){var c=b.position.left,e=c+this.n.outerWidth(!0)-1;this.P(this.D(c),this.D(e));this.M()},ka:function(){this.o();this.N()},ua:function(){var a=this.g;this.g=this.h;this.h=a;this.g.v("ui-rangeSlider-rightHandle").p("ui-rangeSlider-leftHandle");
this.h.p("ui-rangeSlider-rightHandle").v("ui-rangeSlider-leftHandle")},X:function(a,b){var c=this.c.min,e=this.c.max;if(b.ga[0]==this.g[0])c=this.D(b.position.left);else if(b.ga[0]==this.h[0])e=this.D(b.position.left-1+b.ga.outerWidth(!0));else return;if(c>e){this.ua();var f=c,c=e,e=f}this.F(c,e)},Y:function(){this.o();this.N()},la:function(a,b){this.s("valuesChanging");var c=!1;if(a&&!this.i.min)this.s("minValueChanging"),c=this.i.min=!0;if(b&&!this.i.max)this.s("maxValueChanging"),c=this.i.max=
!0;c&&this.qa()},N:function(){var a=this.Q=Math.random();setTimeout(c.f(function(){this.ma(a)},this),200)},ma:function(a){if(this.Q==a&&!this.n.fa("ui-draggable-dragging")&&!this.g.fa("ui-draggable-dragging")&&!this.h.fa("ui-draggable-dragging")){a=!1;if(this.i.min)this.i.min=!1,this.s("minValueChanged"),a=!0;if(this.i.max)this.i.max=!1,this.s("maxValueChanged"),a=!0;a&&this.s("valuesChanged");this.na()}},Ga:function(a,b){this.P(a,b);this.M()},P:function(a,b){var c=this.c,e=Math.abs(b-a);if(e>=this.options.e.max-
this.options.e.min)this.c.min=this.options.e.min,this.c.max=this.options.e.max;else{var f={min:Math.min(b,a),max:Math.max(a,b)};if(f.min<this.options.e.min)f.min=this.options.e.min,f.max=f.min+e;else if(f.max>this.options.e.max)f.max=this.options.e.max,f.min=f.max-e;this.c=f}this.la(c.min!=this.c.min,c.max!=this.c.max);this.N()},pa:function(){this.L();this.o()},ra:function(){this.u=Math.random();this.I=0;this.J(-1,this.u)},sa:function(){this.u=Math.random();this.I=0;this.J(1,this.u)},J:function(a,
b){b==this.u&&(this.R(a*(Math.min(Math.floor(this.I/5)+1,4)/4)),this.I++,setTimeout(c.f(function(){this.J(a,b)},this),50))},ta:function(){this.u=Math.random()},va:function(a,b,c,e){if(this.options.S=="zoom")return this.ia(-e),!1},wa:function(a,b,c,e){if(this.options.S=="scroll")return this.R(-e),!1},T:function(a,b){a===d&&(a=c("<div class='ui-rangeSlider-label'/>").p(b).b("position","absolute"),this.element.append(a),this.$());return a},W:function(a){a!==d&&(a.remove(),a=d);return a},U:function(){this.a.left=
this.T(this.a.left,"ui-rangeSlider-leftLabel");this.a.right=this.T(this.a.right,"ui-rangeSlider-rightLabel");this.options.z=="change"?(this.a.left.b("display","none"),this.a.right.b("display","none"),this.a.q=!1,this.a.r=!1):(this.a.q=!0,this.a.r=!0,this.a.left.b("display","block"),this.a.right.b("display","block"),this.o())},K:function(){this.a.left=this.W(this.a.left);this.a.right=this.W(this.a.right)},Z:function(a,b){var c=this.g.H().top-a.outerHeight(!0),e=a.offsetParent(),f=b-e.H().left;c-=e.H().top;
a.b("left",f).b("top",c)},$:function(){if(this.a.left!==d&&this.a.right!==d){this.a.left.text(this.B(this.c.min));this.a.right.text(this.B(this.c.max));var a=this.a.q?this.a.left.outerWidth(!0):0,b=this.a.r?this.a.right.outerWidth(!0):0,g=c(window).width()-b,e=Math.max(0,this.g.H().left+this.g.outerWidth(!0)/2-a/2),b=Math.min(g,this.h.H().left+this.h.outerWidth(!0)/2-b/2);e+a>=b&&(e=Math.max(0,e-(e+a-b)/2),b=Math.min(g,e+a),e=Math.max(0,b-a));this.a.q&&this.Z(this.a.left,e);this.a.r&&this.Z(this.a.right,
b)}},B:function(a){return typeof this.options.G!="undefined"&&this.options.G!==d?this.options.G(a):this.V(a)},V:function(a){return Math.round(a)},qa:function(){if(this.options.z=="change"&&!this.Ha){if(this.i.min&&!this.a.q)this.a.left.stop(!0,!0).Aa(this.options.da),this.a.q=!0;if(this.i.max&&!this.a.r)this.a.r=!0,this.a.right.stop(!0,!0).Aa(this.options.da)}},na:function(){if(this.options.z=="change"&&this.a.left!==d&&this.a.right!==d)this.a.q=!1,this.a.r=!1,this.a.left.stop(!0,!0).ya(this.options.ba).Ba(this.options.ea),
this.a.right.stop(!0,!0).ya(this.options.ba).Ba(this.options.ea)},m:function(a,b){if(typeof a!="undefined"&&typeof b!="undefined")this.Ca=!1,this.F(a,b),this.Ca=!0;return this.c},min:function(a){return this.m(a,this.c.max).min},max:function(a){return this.m(this.c.min,a).max},ia:function(a){var b=this.c.max-this.c.min;this.F(this.c.min+a*this.options.A*b/200,this.c.max-a*this.options.A*b/200)},Ka:function(a){this.ia(-a)},scrollLeft:function(a){typeof a=="undefined"&&(a=1);this.R(-a)},R:function(a){typeof a==
"undefined"&&(a=1);var b=this.c.max-this.c.min;this.F(this.c.min+a*this.options.A*b/100,this.c.max+a*this.options.A*b/100)},za:function(){this.element.v("ui-rangeSlider-withArrows").v("ui-rangeSlider-noArrow");this.n.detach();this.g.detach();this.h.detach();this.t.detach();this.j.detach();this.d.left.detach();this.d.right.detach();this.element.v("ui-rangeSlider");this.K();delete this.options;c.Ea.prototype.za.apply(this,arguments)}})})(jQuery);(function(c){c.Da("ui.dateRangeSlider",c.l.k,{options:{e:{min:new Date(2010,0,1),max:new Date(2012,0,1)},w:{min:new Date(2010,1,11),max:new Date(2011,1,11)}},O:function(a,b){(a=="defaultValues"||a=="bounds")&&typeof b!="undefined"&&b!==d&&typeof b.min!="undefined"&&typeof b.max!="undefined"&&b.min instanceof Date&&b.max instanceof Date?c.l.k.prototype.O.apply(this,[a,{min:b.min.valueOf(),max:b.max.valueOf()}]):c.l.k.prototype.O.apply(this,arguments)},ha:function(a){if(a=="bounds"||a=="defaultValues"){var b=
c.l.k.prototype.ha.apply(this,arguments);return{min:new Date(b.min),max:new Date(b.max)}}return c.l.k.prototype.ha.apply(this,arguments)},V:function(a){var b=a.getMonth()+1,c=a.getDate();return""+a.getFullYear()+"-"+(b<10?"0"+b:b)+"-"+(c<10?"0"+c:c)},B:function(a){return c.l.k.prototype.B.apply(this,[new Date(a)])},m:function(a,b){var g=d,g=typeof a!="undefined"&&typeof b!="undefined"&&a instanceof Date&&b instanceof Date?c.l.k.prototype.m.apply(this,[a.valueOf(),b.valueOf()]):c.l.k.prototype.m.apply(this,
arguments);return{min:new Date(g.min),max:new Date(g.max)}},min:function(a){if(typeof a!="undefined"&&a instanceof Date)return new Date(c.l.k.prototype.min.apply(this,[a.valueOf()]));return new Date(c.l.k.prototype.min.apply(this))},max:function(a){if(typeof a!="undefined"&&a instanceof Date)return new Date(c.l.k.prototype.max.apply(this,[a.valueOf()]));return new Date(c.l.k.prototype.max.apply(this))}})})(jQuery);
